title: Nathan Bijnens
author: Nathan Bijnens

url: https://nathan.gs

description: > # this means to ignore newlines
  [Sr. Cloud Solution Architect Manager, Data & AI](/cv/) at [Microsoft Belux](/cv/),
  fascinated with Big Data, AI, Data Mesh, Event Driven Systems, NixOS and home automation. [Speaker](/presentations/)
  on Big Data, AI and Spark. 

twitter_username: nathan_gs
twitter:
  username: nathan_gs
github_username:  nathan-gs

social:
  name: Nathan Bijnens
  links:
    - https://twitter.com/nathan_gs
    - https://www.facebook.com/nathan.gs
    - https://www.linkedin.com/in/nbijnens
    - https://github.com/nathan-gs

logo: /assets/nathan-circle.png


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - presentations.html
 - cv/index.html

collections:
  post_tags:
    permalink: /tags/:name
    output: true

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - 'cv/Nathan Bijnens.pdf'
  - .vscode
  - .bundle
  - .jekyll-cache
  - bin
  - "*.nix"
  - devenv.lock
  - devenv.nix

google_analytics: UA-12327464-1

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 5
paginate_path: /page:num/

disqus:
  shortname: nathan

defaults:
  - scope:
      path: "cv/Nathan Bijnens.pdf"
    values:
      sitemap: false
  - scope:
      path: ''
      type: post_tags
    values:
      permalink: "/tags/:name/"
      layout: tag
  - scope:
      type: posts
    values:
      layout: post
      
kramdown:
  input: GFM
  syntax_highlighter: rouge

  # https://github.com/jekyll/jekyll/issues/4619#issuecomment-191267346
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1