title: Nathan Bijnens
author: Nathan Bijnens

# Edit _includes/snippers/description
description: > # this means to ignore newlines
  Fascinated with Big Data & IoT. [Speaker](/presentations/)
  on IoT, Big Data and the Kappa & Lambda Architecture and Spark. 
  <br/>Cloud Solution Architect, Advanced Analytics + AI @ Microsoft.

twitter_username: nathan_gs
github_username:  nathan-gs


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - presentations.html
 - cv/index.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-12327464-1

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/