title: Nathan Bijnens
author: Nathan Bijnens
email: nathan@nathan.gs

description: > # this means to ignore newlines
  Fascinated with Big Data & IoT. Speaker on IoT, 
  Big Data and the Kappa & Lambda Architecture and Spark. 
  Cloud Solution Architect, Advanced Analytics + AI @ Microsoft.

twitter_username: nathan_gs
github_username:  nathan-gs


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

google_analytics: UA-12327464-1

plugins:
  - jekyll-seo-tag